### ISSUE TITLE
No Issue Just a suggestion

### ISSUE THREAD

**Issue by UltraKMovies** [MrAfitol/SCP-1162#2]
I use custom maps in my server. I want to change the spawn location of 1162 to a other rooms x y z cords.

**Comment by MrAfitol** [comment]
Yes, it's possible, I'll try to find something, I'll let you know if I do something about it

**Comment by MrAfitol** [comment]
Done in the new version [1.2.2](https://github.com/MrAfitol/SCP-1162/releases/tag/1.2.2)
